### ISSUE TITLE
docs

### ISSUE THREAD

**Issue by xrotwang** [lmaurits/BEASTling#156]
- [x] old year in `docs/conf.py`
- [x] link to http://cldf.clld.org rather than to the repository on github

**Comment by lmaurits** [comment]
Where is the link to the CLLD repo?  I just did a `grep -i clld docs/*.rst` and the only link I see is to exactly the URL you gave above?

**Comment by xrotwang** [comment]
http://beastling.readthedocs.io/en/latest/data.html#cldf-format

**Comment by xrotwang** [comment]
So it probably is already fixed, just not updated on readthedocs

**Comment by lmaurits** [comment]
Nope, not fixed, I was grepping for clld not cldf, so it didn't turn up.  Fixing now.
